-- Imported from base-legado/modelo_importacao_fstd_legado.xlsx, sheet IMPORTAR_LEGADO.
create table if not exists public.fstd_legado (
  legado_id bigint generated by default as identity primary key,
  codigo_loja text not null, numero_nfd text not null, id text not null, numero_controle text, data_preenchimento timestamptz, responsavel_fstd text, motivo text, qtd_total_galinha bigint, qtd_retorno_galinha bigint, qtd_total_codorna bigint, qtd_retorno_codorna bigint, origem text not null,
  created_at timestamptz not null default now()
);
create index if not exists fstd_legado_id_idx on public.fstd_legado (id);
create index if not exists fstd_legado_lookup_idx on public.fstd_legado (codigo_loja, numero_nfd);
alter table public.fstd_legado enable row level security;
revoke all on table public.fstd_legado from anon;
grant select on table public.fstd_legado to authenticated;
drop policy if exists fstd_legado_select_authorized on public.fstd_legado;
create policy fstd_legado_select_authorized on public.fstd_legado for select to authenticated using ((select app_private.is_current_user_gerencial_ativo()) or exists (select 1 from public.usuarios u where u.auth_user_id=(select auth.uid()) and u.ativo is true));

create or replace function public.obter_fstd_legado(p_codigo_loja text, p_numero_nfd text)
returns setof public.fstd_legado language sql stable security invoker set search_path=public as $$
  select * from public.fstd_legado where codigo_loja=trim(p_codigo_loja) and numero_nfd=trim(p_numero_nfd) order by legado_id;
$$;
revoke all on function public.obter_fstd_legado(text,text) from public, anon;
grant execute on function public.obter_fstd_legado(text,text) to authenticated;
notify pgrst, 'reload schema';